game_srcs = files(
    'm_actor.c',
    'm_actor_dlftbls.c',
    'm_actor_shadow.c',
    'm_address_ovl.c',
    'm_all_grow.c',
    'm_all_grow_ovl.c',
    'm_bank_ovl.c',
    'm_banti.c',
    'm_bg_item.c',
    'm_bg_tex.c',
    'm_bgm.c',
    'm_birthday_ovl.c',
    'm_board_ovl.c',
    'm_calendar.c',
    'm_calendar_ovl.c',
    'm_camera2.c',
    'm_card.c',
    'm_catalog_ovl.c',
    'm_choice.c',
    'm_clip.c',
    'm_cockroach.c',
    'm_collision_bg.c',
    'm_collision_obj.c',
    'm_common_data.c',
    'm_controller.c',
    'm_cpak.c',
    'm_cpedit_ovl.c',
    'm_cpmail_ovl.c',
    'm_cporiginal_ovl.c',
    'm_cpwarning_ovl.c',
    'm_debug.c',
    'm_debug_display.c',
    'm_debug_hayakawa.c',
    'm_debug_mode.c',
    'm_demo.c',
    'm_design_ovl.c',
    'm_diary.c',
    'm_diary_ovl.c',
    'm_eappli.c',
    'm_editEndChk_ovl.c',
    'm_editor_ovl.c',
    'm_event.c',
    'm_event_map_npc.c',
    'm_fbdemo.c',
    'm_fbdemo_fade.c',
    'm_fbdemo_triforce.c',
    'm_fbdemo_wipe1.c',
    'm_field_assessment.c',
    'm_field_info.c',
    'm_field_make.c',
    'm_fishrecord.c',
    'm_flashrom.c',
    'm_font.c',
    'm_fuusen.c',
    'm_game_dlftbls.c',
    'm_gba_ovl.c',
    'm_hand_ovl.c',
    'm_handbill.c',
    'm_haniwa_ovl.c',
    'm_haniwaPortrait_ovl.c',
    'm_hboard_ovl.c',
    'm_home.c',
    'm_house.c',
    'm_huusui_room.c',
    'm_huusui_room_ovl.c',
    'm_inventory_ovl.c',
    'm_island.c',
    'm_item_name.c',
    'm_kabu_manager.c',
    'm_kankyo.c',
    'm_land.c',
    'm_ledit_ovl.c',
    'm_lib.c',
    'm_lights.c',
    'm_mail.c',
    'm_mail_check.c',
    'm_mail_check_ovl.c',
    'm_mail_password_check.c',
    'm_mailbox_ovl.c',
    'm_malloc.c',
    'm_map_ovl.c',
    'm_mark_room.c',
    'm_mark_room_ovl.c',
    'm_melody.c',
    'm_mscore_ovl.c',
    'm_msg.c',
    'm_museum.c',
    'm_museum_display.c',
    'm_mushroom.c',
    'm_music_ovl.c',
    'm_name_table.c',
    'm_needlework.c',
    'm_needlework_ovl.c',
    'm_notice.c',
    'm_notice_ovl.c',
    'm_npc.c',
    'm_npc_schedule.c',
    'm_npc_walk.c',
    'm_olib.c',
    'm_passwordChk_ovl.c',
    'm_passwordMake_ovl.c',
    'm_pause.c',
    'm_play.c',
    'm_player.c',
    'm_player_call.c',
    'm_player_lib.c',
    'm_police_box.c',
    'm_post_office.c',
    'm_prenmi.c',
    'm_private.c',
    'm_quest.c',
    'm_random_field.c',
    'm_random_field_ovl.c',
    'm_rcp.c',
    'm_repay_ovl.c',
    'm_roll_lib.c',
    'm_room_type.c',
    'm_scene.c',
    'm_scene_ftr.c',
    'm_scene_table.c',
    'm_select.c',
    'm_shop.c',
    'm_skin_matrix.c',
    'm_snowman.c',
    'm_soncho.c',
    'm_start_data_init.c',
    'm_string.c',
    'm_submenu.c',
    'm_submenu_ovl.c',
    'm_tag_ovl.c',
    'm_time.c',
    'm_timeIn_ovl.c',
    'm_titledemo.c',
    'm_trademark.c',
    'm_train_control.c',
    'm_vibctl.c',
    'm_view.c',
    'm_warning_ovl.c',
    'm_watch_my_step.c'
)

game_lib = static_library('game',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: game_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += game_lib