subdir('npc')

actor_srcs = files(
    'ac_airplane.c',
    'ac_animal_logo.c',
    'ac_ant.c',
    'ac_aprilfool_control.c',
    'ac_arrange_ftr.c',
    'ac_arrange_room.c',
    'ac_ball.c',
    'ac_balloon.c',
    'ac_bee.c',
    'ac_birth_control.c',
    'ac_boat.c',
    'ac_boat_demo.c',
    'ac_boxManager.c',
    'ac_boxMove.c',
    'ac_boxTrick01.c',
    'ac_br_shop.c',
    'ac_bridge_a.c',
    'ac_broker_design.c',
    'ac_buggy.c',
    'ac_conveni.c',
    'ac_cottage.c',
    'ac_count02.c',
    'ac_countdown.c',
    'ac_depart.c',
    'ac_douzou.c',
    'ac_dummy.c',
    'ac_dump.c',
    'ac_effectbg.c',
    'ac_event_manager.c',
    'ac_fallS.c',
    'ac_fallSESW.c',
    'ac_field_draw.c',
    'ac_fieldm_draw.c',
    'ac_flag.c',
    'ac_fuusen.c',
    'ac_garagara.c',
    'ac_ghog.c',
    'ac_goza.c',
    'ac_groundhog_control.c',
    'ac_gyo_kage.c',
    'ac_gyo_kaseki.c',
    'ac_gyo_release.c',
    'ac_gyo_test.c',
    'ac_gyoei.c',
    'ac_handOverItem.c',
    'ac_haniwa.c',
    'ac_hatumode_control.c',
    'ac_house.c',
    'ac_house_clock.c',
    'ac_house_goki.c',
    'ac_htable.c',
    'ac_ins_amenbo.c',
    'ac_ins_batta.c',
    'ac_ins_chou.c',
    'ac_ins_dango.c',
    'ac_ins_goki.c',
    'ac_ins_hitodama.c',
    'ac_ins_hotaru.c',
    'ac_ins_ka.c',
    'ac_ins_kabuto.c',
    'ac_ins_kera.c',
    'ac_ins_mino.c',
    'ac_ins_semi.c',
    'ac_ins_tentou.c',
    'ac_ins_tonbo.c',
    'ac_insect.c',
    'ac_intro_demo.c',
    'ac_kago.c',
    'ac_kamakura.c',
    'ac_kamakura_indoor.c',
    'ac_koinobori.c',
    'ac_lighthouse_switch.c',
    'ac_lotus.c',
    'ac_mailbox.c',
    'ac_mbg.c',
    'ac_mikanbox.c',
    'ac_mikuji.c',
    'ac_misin.c',
    'ac_mscore_control.c',
    'ac_mural.c',
    'ac_museum.c',
    'ac_museum_fish.c',
    'ac_museum_fossil.c',
    'ac_museum_indoor.c',
    'ac_museum_insect.c',
    'ac_museum_picture.c',
    'ac_my_house.c',
    'ac_my_indoor.c',
    'ac_my_room.c',
    'ac_nameplate.c',
    'ac_needlework_indoor.c',
    'ac_needlework_shop.c',
    'ac_police_box.c',
    'ac_post_office.c',
    'ac_present_demo.c',
    'ac_psnowman.c',
    'ac_pterminal.c',
    'ac_quest_manager.c',
    'ac_quest_talk_fj_init.c',
    'ac_quest_talk_greeting.c',
    'ac_quest_talk_init.c',
    'ac_quest_talk_island.c',
    'ac_quest_talk_normal_init.c',
    'ac_radio.c',
    'ac_reserve.c',
    'ac_reset_demo.c',
    'ac_ride_off_demo.c',
    'ac_rope.c',
    'ac_s_car.c',
    'ac_sample.c',
    'ac_set_manager.c',
    'ac_set_npc_manager.c',
    'ac_set_ovl_gyoei.c',
    'ac_set_ovl_insect.c',
    'ac_shop.c',
    'ac_shop_design.c',
    'ac_shop_goods.c',
    'ac_shop_indoor.c',
    'ac_shop_level.c',
    'ac_shop_manekin.c',
    'ac_shop_umbrella.c',
    'ac_shrine.c',
    'ac_sign.c',
    'ac_snowman.c',
    'ac_station.c',
    'ac_structure.c',
    'ac_super.c',
    'ac_tama.c',
    'ac_tent.c',
    'ac_tokyoso_control.c',
    'ac_tools.c',
    'ac_toudai.c',
    'ac_train0.c',
    'ac_train1.c',
    'ac_train_door.c',
    'ac_train_window.c',
    'ac_tukimi.c',
    'ac_tunahiki_control.c',
    'ac_turi.c',
    'ac_uki.c',
    'ac_weather.c',
    'ac_weather_fine.c',
    'ac_weather_leaf.c',
    'ac_weather_rain.c',
    'ac_weather_sakura.c',
    'ac_weather_snow.c',
    'ac_windmill.c',
    'ac_yatai.c',
)

actor_lib = static_library('actor',
    include_directories: project_includes,
    pic: false,
    dependencies: [libporpoise_dep, gafe_assets_dep],
    sources: actor_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += actor_lib