subdir('event')

actor_npc_srcs = files(
    'ac_countdown_npc0.c',
    'ac_countdown_npc1.c',
    'ac_go_home_npc.c',
    'ac_groundhog_npc0.c',
    'ac_halloween_npc.c',
    'ac_hanabi_npc0.c',
    'ac_hanabi_npc1.c',
    'ac_hanami_npc0.c',
    'ac_hanami_npc1.c',
    'ac_harvest_npc0.c',
    'ac_harvest_npc1.c',
    'ac_hatumode_npc0.c',
    'ac_kamakura_npc0.c',
    'ac_normal_npc.c',
    'ac_npc.c',
    'ac_npc2.c',
    'ac_npc_conv_master.c',
    'ac_npc_curator.c',
    'ac_npc_depart_master.c',
    'ac_npc_engineer.c',
    'ac_npc_guide.c',
    'ac_npc_guide2.c',
    'ac_npc_hem.c',
    'ac_npc_majin.c',
    'ac_npc_majin2.c',
    'ac_npc_majin3.c',
    'ac_npc_majin4.c',
    'ac_npc_majin5.c',
    'ac_npc_mamedanuki.c',
    'ac_npc_mask_cat.c',
    'ac_npc_mask_cat2.c',
    'ac_npc_needlework.c',
    'ac_npc_p_sel.c',
    'ac_npc_p_sel2.c',
    'ac_npc_police.c',
    'ac_npc_police2.c',
    'ac_npc_post_girl.c',
    'ac_npc_post_man.c',
    'ac_npc_rcn_guide.c',
    'ac_npc_rcn_guide2.c',
    'ac_npc_restart.c',
    'ac_npc_rtc.c',
    'ac_npc_sendo.c',
    'ac_npc_shasho.c',
    'ac_npc_shop_master.c',
    'ac_npc_shop_mastersp.c',
    'ac_npc_sleep_obaba.c',
    'ac_npc_soncho.c',
    'ac_npc_station_master.c',
    'ac_npc_super_master.c',
    'ac_npc_totakeke.c',
    'ac_present_npc.c',
    'ac_taisou_npc0.c',
    'ac_tamaire_npc0.c',
    'ac_tamaire_npc1.c',
    'ac_tokyoso_npc0.c',
    'ac_tokyoso_npc1.c',
    'ac_tukimi_npc0.c',
    'ac_tukimi_npc1.c',
    'ac_tunahiki_npc0.c',
    'ac_tunahiki_npc1.c',
    'ac_turi_npc0.c',
)

actor_npc_lib = static_library('actor_npc',
    include_directories: project_includes,
    pic: false,
    dependencies: [libporpoise_dep, gafe_assets_dep],
    sources: actor_npc_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += actor_npc_lib