libultra_srcs = files(
    'gu/coss.c',
    'gu/lookat.c',
    'gu/lookathil.c',
    'gu/mtxutil.c',
    'gu/normalize.c',
    'gu/ortho.c',
    'gu/perspective.c',
    'gu/rotate.c',
    'gu/scale.c',
    'gu/sins.c',
    'gu/translate.c',
    'contquery.c',
    'contreaddata.c',
    'controller.c',
    'contsetch.c',
    'createmesgqueue.c',
    'createthread.c',
    'destroythread.c',
    'getthreadid.c',
    'gettime.c',
    'initialize.c',
    'recvmesg.c',
    'sendmesg.c',
    'setthreadpri.c',
    'settimer.c',
    'shutdown.c',
    'startthread.c',
    'stoptimer.c',
    'timerintr.c',
    'ultra.c',
    'xldtob.c',
    'xlitob.c',
    'xprintf.c'
)

libultra_lib = static_library('ultra',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: libultra_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += libultra_lib