jaudio_NES_internal_srcs = files(
    'aictrl.cpp',
    'astest.cpp',
    'audiothread.cpp',
    'cpubuf.cpp',
    'dspboot.cpp',
    'dspbuf.cpp',
    'dspproc.cpp',
    'dummyrom.cpp',
    'dvdthread.cpp',
    'neosthread.cpp',
    'os.cpp',
    'playercall.cpp',
    'random.cpp',
    'sample.cpp',
    'streamctrl.cpp',
    'sub_sys.cpp',
    'track.cpp',
    'aramcall.cpp',
    'audioconst.cpp',
    'audiotable.cpp',
    'audiowork.cpp',
    'bankdrv.cpp',
    'bankread.cpp',
    'centcalc.cpp',
    'channel.cpp',
    'cmdstack.cpp',
    'connect.cpp',
    'driver.cpp',
    'driverinterface.cpp',
    'dsp_cardunlock.cpp',
    'dsp_GBAKey.cpp',
    'dspdriver.cpp',
    'dspinterface.cpp',
    'effect.cpp',
    'fat.cpp',
    'fxinterface.cpp',
    'heapctrl.cpp',
    'ipldec.cpp',
    'ja_calc.cpp',
    'jammain_2.cpp',
    'jamosc.cpp',
    'memory.cpp',
    'midplay.cpp',
    'noteon.cpp',
    'oneshot.cpp',
    'rate.cpp',
    'rspsim.cpp',
    'seqsetup.cpp',
    'system.cpp',
    'tables.cpp',
    'waveread.cpp',
)

jaudio_NES_internal_lib = static_library('jaudio_NES_internal',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: jaudio_NES_internal_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += jaudio_NES_internal_lib