effect_srcs = files(
    'ef_ami_mizu.c',
    'ef_anahikari.c',
    'ef_ase.c',
    'ef_ase2.c',
    'ef_ase_ch.c',
    'ef_break_axe.c',
    'ef_bubu.c',
    'ef_buruburu.c',
    'ef_bush_happa.c',
    'ef_bush_yuki.c',
    'ef_car_blight.c',
    'ef_car_light.c',
    'ef_clacker.c',
    'ef_coin.c',
    'ef_dash_asimoto.c',
    'ef_dig_hole.c',
    'ef_dig_mud.c',
    'ef_dig_scoop.c',
    'ef_douzou_light.c',
    'ef_doyon.c',
    'ef_dust.c',
    'ef_effect_control.c',
    'ef_flash.c',
    'ef_footprint.c',
    'ef_furo_yuge.c',
    'ef_gimonhu.c',
    'ef_goki.c',
    'ef_ha.c',
    'ef_halloween.c',
    'ef_halloween_smoke.c',
    'ef_hanabi_botan1.c',
    'ef_hanabi_botan2.c',
    'ef_hanabi_dummy.c',
    'ef_hanabi_hoshi.c',
    'ef_hanabi_set.c',
    'ef_hanabi_switch.c',
    'ef_hanabi_yanagi.c',
    'ef_hanabira.c',
    'ef_hanatiri.c',
    'ef_hirameki_den.c',
    'ef_hirameki_hikari.c',
    'ef_ikigire.c',
    'ef_impact_star.c',
    'ef_kagu_happa.c',
    'ef_kamifubuki.c',
    'ef_kangaeru.c',
    'ef_kantanhu.c',
    'ef_kasamizu.c',
    'ef_kasamizutama.c',
    'ef_kaze.c',
    'ef_kaze_happa.c',
    'ef_kigae.c',
    'ef_kigae_light.c',
    'ef_kikuzu.c',
    'ef_killer.c',
    'ef_kisha_kemuri.c',
    'ef_konpu.c',
    'ef_kpun.c',
    'ef_kyousou_onpu.c',
    'ef_lamp_light.c',
    'ef_lovelove.c',
    'ef_lovelove2.c',
    'ef_lovelove_heart.c',
    'ef_make_hem.c',
    'ef_mizutama.c',
    'ef_motiyuge.c',
    'ef_muka.c',
    'ef_naku.c',
    'ef_namida.c',
    'ef_neboke.c',
    'ef_neboke_akubi.c',
    'ef_neboke_awa.c',
    'ef_night13_moon.c',
    'ef_night15_moon.c',
    'ef_ongen.c',
    'ef_otikomi.c',
    'ef_otosiana.c',
    'ef_pun.c',
    'ef_pun_sekimen.c',
    'ef_pun_yuge.c',
    'ef_reset_hole.c',
    'ef_room_sunshine.c',
    'ef_room_sunshine_minsect.c',
    'ef_room_sunshine_museum.c',
    'ef_room_sunshine_police.c',
    'ef_room_sunshine_posthouse.c',
    'ef_sandsplash.c',
    'ef_shock.c',
    'ef_shooting.c',
    'ef_shooting_kira.c',
    'ef_shooting_set.c',
    'ef_siawase_hana.c',
    'ef_siawase_hana_ch.c',
    'ef_siawase_hikari.c',
    'ef_sibuki.c',
    'ef_situren.c',
    'ef_slip.c',
    'ef_slip_footprint.c',
    'ef_soba_yuge.c',
    'ef_steam.c',
    'ef_string.c',
    'ef_suisou_awa.c',
    'ef_swing_axe.c',
    'ef_swing_net.c',
    'ef_swing_rod.c',
    'ef_taberu.c',
    'ef_takurami.c',
    'ef_takurami_kira.c',
    'ef_tamaire.c',
    'ef_tape.c',
    'ef_tent_lamp.c',
    'ef_tumble.c',
    'ef_tumble_bodyprint.c',
    'ef_tumble_dust.c',
    'ef_turi_hamon.c',
    'ef_turi_hane0.c',
    'ef_turi_hane1.c',
    'ef_turi_mizu.c',
    'ef_turi_suiteki.c',
    'ef_turn_asimoto.c',
    'ef_turn_footprint.c',
    'ef_uranai.c',
    'ef_wait_asimoto.c',
    'ef_walk_asimoto.c',
    'ef_warau.c',
    'ef_yajirushi.c',
    'ef_young_tree.c',
    'ef_yukidama.c',
    'ef_yukidaruma.c',
    'ef_yukihane.c'
)

effect_lib = static_library('effect',
    include_directories: project_includes,
    pic: false,
    dependencies: [libporpoise_dep, gafe_assets_dep],
    sources: effect_srcs,
    native: build_target != 'gc'
)
animalcrossing_libs += effect_lib