subdir('Famicom')
subdir('jaudio_NES')
subdir('JSystem')
subdir('libc64')
subdir('libforest')
subdir('libjsys')
subdir('libu64')
subdir('libultra')

boot_srcs = files(
    'bootdata/gam_win1.c',
    'bootdata/gam_win2.c',
    'bootdata/gam_win3.c',
    'bootdata/logo_nin.c',
    #'GBA2/JoyBoot.c'
    'boot.c',
    'dvderr.c',
    'initial_menu.c',
    'jsyswrap.cpp',
    'nintendo_hi_0.c',
    'version.c'
)