subdir('static')

foresta_srcs = files(
    'audio.c',
    'c_keyframe.c',
    'ev_cherry_manager.c',
    'evw_anime.c',
    #'executor.c' TODO
    'f_furniture.c',
    'famicom_emu.c',
    'first_game.c',
    'game.c',
    'gamealloc.c',
    'gfxalloc.c',
    'graph.c',
    'irqmgr.c',
    'lb_reki.c',
    'lb_rtc.c',
    'main.c',
    'padmgr.c',
    'player_select.c',
    'PreRender.c',
    's_cpak.c',
    'save_menu.c',
    'second_game.c',
    'THA_GA.c',
    'TwoHeadArena.c',
    'zurumode.c'
)